- id: "/"
  title: "Conferenza Italiana Studenti di Fisica 2018"
  description: "La <b>CISF</b> costituisce il principale evento annuale organizzato dall'<b>Associazione Italiana Studenti di Fisica</b> (AISF).
Giunta alla sua IV edizione, la CISF 2018 si svolgerà a <b>Pisa</b>, dove circa <b>150 studenti</b>
provenienti da tutta Italia avranno la possibilità di visitare i maggiori centri di ricerca e laboratori
della zona, seguire una serie di interventi di illustri professori e ricercatori, conoscere e vivere la quotidianità dell'ambiente universitario pisano,
reso unico dalla compresenza dell'Università di Pisa, Scuola Normale Superiore, Scuola Superiore Sant'Anna, INFN e CNR."
  keywords: "CISF conferenza aisf associazione italiana studenti di fisica iaps pisa visita virgo"
